// countriesData.js

export const blockedCountries = [
    'Angola',
    'Bosnia and Herzegovina',
    'Croatia',
    'Cuba',
    'Iran',
    'Iraq',
    'Lebanon',
    'Liberia',
    'Libya',
    'Malaysia',
    'Montenegro',
    'Myanmar',
    'North Korea',
    'Romania',
    'Russian Federation',
    'Serbia',
    'Sierra Leone',
    'Slovenia',
    'Sudan',
    'Ukraine',
    'Yugoslav Republic of Macedonia / Republic of Macedonia',
  ];
  
  export const countries = [
    'Select a country', 
    'Albania',
    'Algeria',
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Afghanistan",
    "Bahamas",
    "Botswana",
    "China",
    "Canada",
    'Iran',
    'Iraq',
    'Lebanon',
    'Liberia',
    'Libya',
    "Kenya",
    'Malaysia',
    'Montenegro',
    'Myanmar',
    'North Korea',
    "Namibia",
    'Romania',
    'Russian Federation',
    'Serbia',
    'Sierra Leone',
    'Slovenia',
    'Sudan',
    "South Africa",
    "Tanzania",
    "United Kingdom",
    "United States",
    "Venezuela",
    "Zambia",
    "Zimbabwe"
  ];
  